#ddl Linguagem de Definição de Dados

DROP DATABASE aula00;
 
CREATE DATABASE aula00;

USE aula00;

CREATE TABLE cliente(
	CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NULL DEFAULT 18,
    PRIMARY KEY (CPF)
);

CREATE TABLE produto(
	ID INT NOT NULL auto_increment, # INTEIRO, NÃO NULO, AUTO INCREMENTO
    NOME VARCHAR(100) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR NUMERIC(9,2) NULL, # 9 digitos, 2 casas decimais 
    PRIMARY KEY(ID)
);

CREATE TABLE VENDA(
	ID INT NOT NULL AUTO_INCREMENT,
    CPF_CLIENTE VARCHAR(14) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DATA DATETIME NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_VENDACLIENTE FOREIGN KEY(CPF_CLIENTE) REFERENCES cliente(CPF), 
    # 'constraint': palavra reservada para dar nome a regra
    CONSTRAINT FK_VENDAPRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES produto(ID)
);

# DML - Linguagem de manipulação de dados

# cadastrar cliente
INSERT INTO CLIENTE
VALUES('05389536592','PEDRO',29);

#cadastrar produto
INSERT INTO PRODUTO
VALUES(0,'CAMISA',10,35.50);

INSERT INTO PRODUTO
VALUES(0,'CALÇA',10,90.99);

#Deletar produto cadastrado
DELETE FROM VENDA
WHERE ID = 1

#Atualizar dados do objeto
UPDATE PRODUTO
	SET QUANTIDADE = 20, VALOR = 55.20
    WHERE ID = 2;

INSERT INTO VENDA
VALUES(0,'05389536592',2,'2026-02-03 21:04',2);

# Relatório

CREATE VIEW VW_RELATORIO AS SELECT VE.DATA, VE.CPF_CLIENTE, VE.QUANTIDADE,
	CLI.NOME AS 'CLIENTE', PRO.NOME AS 'PRODUTO', PRO.VALOR, (PRO.VALOR * VE.QUANTIDADE) AS 'TOTAL'
FROM VENDA VE
INNER JOIN CLIENTE CLI ON CLI.CPF = VE.CPF_CLIENTE # cria 'apelido' para cada coluna como 'cli', 've'
INNER JOIN PRODUTO PRO ON PRO.ID = VE.ID_PRODUTO # retorna o join 

SELECT * FROM VW_RELATORIO;

