CREATE DATABASE SENAI;

USE SENAI;

CREATE TABLE LIVRO (
ISBN VARCHAR (100) NOT NULL PRIMARY KEY,
TITULO VARCHAR(100) NOT NULL,
ANO_PUBLICACAO INT,
PRECO NUMERIC(9,2) NOT NULL
);

CREATE TABLE AUTOR(
ID INT NOT NULL PRIMARY KEY auto_increment,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(40) NOT NULL UNIQUE
);

ALTER TABLE LIVRO ADD ID_AUTOR INT NOT NULL;

ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_AUTOR foreign key(ID_AUTOR) REFERENCES AUTOR(ID);

CREATE TABLE ALUNO(
MATRICULA VARCHAR(40) NOT NULL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(40) NULL,
TELEFONE VARCHAR(40) NULL
);

CREATE TABLE EMPRESTIMO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ISBN VARCHAR(100) NOT NULL,
MATRICULA VARCHAR(40) NOT NULL,
DATA DATETIME NULL DEFAULT NOW(),
DIAS INT NULL DEFAULT 1,
CONSTRAINT FK_EMP_LIVRO FOREIGN KEY(ISBN) REFERENCES LIVRO(ISBN),
CONSTRAINT FK_EMP_ALUNO FOREIGN KEY(MATRICULA) REFERENCES ALUNO(MATRICULA)
);

INSERT INTO ALUNO VALUES(
"025.007085","PEDRO CANUTO","05389536592","(71)99958-8950");





