CREATE DATABASE VENDAS;

USE VENDAS;

CREATE TABLE LOJA (
ID INT NOT NULL auto_increment PRIMARY KEY,
NOME_LOJA VARCHAR(100) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENTE (
ID INT NOT NULL auto_increment PRIMARY KEY,
NOME_CLIENTE VARCHAR(100) NOT NULL,
IDADE INT NOT NULL
);

CREATE TABLE PRODUTO(
ID INT NOT NULL auto_increment PRIMARY KEY,
NOME_PRODUTO VARCHAR(100) NOT NULL,
MARCA VARCHAR(100) NOT NULL,
PRECO_UNITARIO NUMERIC (9,2) NOT NULL,
CUSTO_UNITARIO NUMERIC (9,2) NOT NULL
);

CREATE TABLE VENDAS(
ID INT NOT NULL auto_increment PRIMARY KEY,
ID_LOJA INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_PRODUTO INT NOT NULL,
DATA_VENDA DATE NOT NULL,
QTD_VENDIDA INT NOT NULL DEFAULT 1
);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_LOJA foreign key (ID_LOJA) REFERENCES LOJA (ID);
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_CLIENTE foreign key (ID_CLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_PRODUTO foreign key (ID_PRODUTO) REFERENCES PRODUTO (ID);

INSERT INTO LOJA VALUES (0,"LOJA MEG","ENGENHO VELHO");
INSERT INTO LOJA VALUES (0,"LOJA ISAAC","PERO VAZ");
INSERT INTO LOJA VALUES (0,"LOJAS CANUTO", "PERIPERI");

INSERT INTO CLIENTE VALUES (0,"PEDRO","29");
INSERT INTO CLIENTE VALUES(0,"VINI","23");
INSERT INTO CLIENTE VALUES(0,"ISAAC","22");

INSERT INTO PRODUTO VALUES (0,"ÁGUA","INDAIÁ",6.00,0.60);
INSERT INTO PRODUTO VALUES (0,"GELADINHO","MARACUJÁ",5.00,0.50);
INSERT INTO PRODUTO VALUES (0,"PICOLÉ","CAPELINHA",8.00,2.00);
INSERT INTO PRODUTO VALUES (0,"GATORADE","COCA-COLA",10.00,4.00);
UPDATE PRODUTO SET PRECO_UNITARIO = 10 WHERE ID = 1;

INSERT INTO VENDAS VALUES(0,3,2,1,"2026-02-11",1);
INSERT INTO VENDAS VALUES(0,3,1,1,"2026-02-11",1);

SELECT*
FROM VENDAS;

CREATE VIEW VW_RELATORIO AS SELECT VE.ID, VE.QTD_VENDIDA







