
use ecommerce;

SELECT * FROM USERS;
SELECT * FROM ADDRESSES;
SELECT * FROM CATEGORIES;   
SELECT * FROM PRODUCTS;
SELECT * FROM SHOPPING_CART;
SELECT * FROM CART_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PAYMENTS;
SELECT * FROM ORDER_ITEMS;